// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jijoulspwdwqkjtstpuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imppam91bHNwd2R3cWtqdHN0cHVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIzNTA3MzMsImV4cCI6MjA4NzkyNjczM30.zGXwlvI2VNbAHmLRS1gIy3ZdadrT_o5ET86U0rR2wcI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});