// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://spulfrqhoavfsbhclrds.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwdWxmcnFob2F2ZnNiaGNscmRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMDIxMDQsImV4cCI6MjA3MzY3ODEwNH0.cxT9eN5v9EA-eA2GO5_csE3fDNA3ko_joI7tYyDOzhI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});