// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjutdnnqlkujzltpvpwd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqdXRkbm5xbGt1anpsdHB2cHdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk2MjgwNDQsImV4cCI6MjA4NTIwNDA0NH0.WryFQDqp-6WZ-_Z-G6sGY9YXi-JFLyFi4rUfsrnd_cA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});